// Generated by CoffeeScript 1.9.3
(function() {
  var bot;

  bot = __core.bot;

  module.exports = {

    /* == update_nicks (event:names) ==
    Pushes a nick on join
     */
    user_join: {
      event: 'names',
      trigger: function(message) {
        return true;
      },
      action: function(respond, done) {
        var key;
        if (!bot.nicks) {
          bot.nicks = [];
        }
        for (key in bot.nicks) {
          if (!bot.nicks.indexOf(key)) {
            bot.nicks.push(key);
          }
        }
        return done();
      }
    }
  };

}).call(this);
