// Generated by CoffeeScript 1.9.3
(function() {
  var bot;

  bot = __core.bot;

  module.exports = {

    /* == user_join (event:join) ==
    Pushes a nick on join
     */
    user_join: {
      event: 'join',
      trigger: function(message) {
        return true;
      },
      action: function(respond, done) {
        if (!bot.nicks.indexOf(respond.nick)) {
          bot.nicks.push(respond.nick);
        }
        return done();
      }
    }
  };

}).call(this);
