// Generated by CoffeeScript 1.9.3
(function() {
  var _, bot;

  bot = __core.bot;

  _ = require('lodash');

  module.exports = {

    /* == user_part (event:part) ==
    Removes nick on user part
     */
    user_part: {
      event: 'part',
      trigger: function(message) {
        return true;
      },
      action: function(respond, done) {
        if (bot.nicks.indexOf(respond.nick)) {
          _.pull(bot.nicks, respond.nick);
        }
        return done();
      }
    }
  };

}).call(this);
