// Generated by CoffeeScript 1.9.3
(function() {
  var channelSchema, mongoose;

  mongoose = require('mongoose');

  channelSchema = mongoose.Schema({
    tag: String,
    name: String,
    usersSeen: [String],
    currentUsers: [String],
    totalUsers: Number,
    usersAsOfNow: Number,
    highestUserCount: Number,
    messages: Number,
    actions: Number
  });

  module.exports = mongoose.model('Channel', channelSchema);

}).call(this);
